collections:
- community.google
- name: google.cloud
  version: 1.1.3
- community.docker # to use docker
roles:  
- name: geerlingguy.pip # to install docker python library
- name: geerlingguy.docker # to install docker