INSERT INTO public.district (id, name) VALUES (1, 'Aveiro');
INSERT INTO public.district (id, name) VALUES (2, 'Beja');
INSERT INTO public.district (id, name) VALUES (3, 'Braga');
INSERT INTO public.district (id, name) VALUES (4, 'Bragança');
INSERT INTO public.district (id, name) VALUES (5, 'Castelo Branco');
INSERT INTO public.district (id, name) VALUES (6, 'Coimbra');
INSERT INTO public.district (id, name) VALUES (7, 'Faro');
INSERT INTO public.district (id, name) VALUES (8, 'Guarda');
INSERT INTO public.district (id, name) VALUES (9, 'Leiria');
INSERT INTO public.district (id, name) VALUES (10, 'Lisboa');
INSERT INTO public.district (id, name) VALUES (11, 'Portalegre');
INSERT INTO public.district (id, name) VALUES (12, 'Porto');
INSERT INTO public.district (id, name) VALUES (13, 'R. A. Açores');
INSERT INTO public.district (id, name) VALUES (14, 'R. A. Madeira');
INSERT INTO public.district (id, name) VALUES (15, 'Santarém');
INSERT INTO public.district (id, name) VALUES (16, 'Setúbal');
INSERT INTO public.district (id, name) VALUES (17, 'Viana do Castelo');
INSERT INTO public.district (id, name) VALUES (18, 'Vila Real');
INSERT INTO public.district (id, name) VALUES (19, 'Viseu');
INSERT INTO public.district (id, name) VALUES (20, 'Évora');

INSERT INTO public.municipality (id, name, district_id) VALUES (1, 'todos', 1);
INSERT INTO public.municipality (id, name, district_id) VALUES (2, 'Águeda', 1);
INSERT INTO public.municipality (id, name, district_id) VALUES (3, 'Albergaria-a-velha', 1);
INSERT INTO public.municipality (id, name, district_id) VALUES (4, 'Anadia', 1);
INSERT INTO public.municipality (id, name, district_id) VALUES (5, 'Arouca', 1);
INSERT INTO public.municipality (id, name, district_id) VALUES (6, 'Aveiro', 1);
INSERT INTO public.municipality (id, name, district_id) VALUES (7, 'Castelo de Paiva', 1);
INSERT INTO public.municipality (id, name, district_id) VALUES (8, 'Espinho', 1);
INSERT INTO public.municipality (id, name, district_id) VALUES (9, 'Estarreja', 1);
INSERT INTO public.municipality (id, name, district_id) VALUES (10, 'Ílhavo', 1);
INSERT INTO public.municipality (id, name, district_id) VALUES (11, 'Mealhada', 1);
INSERT INTO public.municipality (id, name, district_id) VALUES (12, 'Murtosa', 1);
INSERT INTO public.municipality (id, name, district_id) VALUES (13, 'Oliveira de Azeméis', 1);
INSERT INTO public.municipality (id, name, district_id) VALUES (14, 'Oliveira do Bairro', 1);
INSERT INTO public.municipality (id, name, district_id) VALUES (15, 'Ovar', 1);
INSERT INTO public.municipality (id, name, district_id) VALUES (16, 'Santa Maria da Feira', 1);
INSERT INTO public.municipality (id, name, district_id) VALUES (17, 'São João da Madeira', 1);
INSERT INTO public.municipality (id, name, district_id) VALUES (18, 'Sever do Vouga', 1);
INSERT INTO public.municipality (id, name, district_id) VALUES (19, 'Vagos', 1);
INSERT INTO public.municipality (id, name, district_id) VALUES (20, 'Vale de Cambra', 1);
INSERT INTO public.municipality (id, name, district_id) VALUES (21, 'todos', 2);
INSERT INTO public.municipality (id, name, district_id) VALUES (22, 'Aljustrel', 2);
INSERT INTO public.municipality (id, name, district_id) VALUES (23, 'Almodôvar', 2);
INSERT INTO public.municipality (id, name, district_id) VALUES (24, 'Alvito', 2);
INSERT INTO public.municipality (id, name, district_id) VALUES (25, 'Barrancos', 2);
INSERT INTO public.municipality (id, name, district_id) VALUES (26, 'Beja', 2);
INSERT INTO public.municipality (id, name, district_id) VALUES (27, 'Castro Verde', 2);
INSERT INTO public.municipality (id, name, district_id) VALUES (28, 'Cuba', 2);
INSERT INTO public.municipality (id, name, district_id) VALUES (29, 'Ferreira do Alentejo', 2);
INSERT INTO public.municipality (id, name, district_id) VALUES (30, 'Mértola', 2);
INSERT INTO public.municipality (id, name, district_id) VALUES (31, 'Moura', 2);
INSERT INTO public.municipality (id, name, district_id) VALUES (32, 'Odemira', 2);
INSERT INTO public.municipality (id, name, district_id) VALUES (33, 'Ourique', 2);
INSERT INTO public.municipality (id, name, district_id) VALUES (34, 'Serpa', 2);
INSERT INTO public.municipality (id, name, district_id) VALUES (35, 'Vidigueira', 2);
INSERT INTO public.municipality (id, name, district_id) VALUES (36, 'todos', 3);
INSERT INTO public.municipality (id, name, district_id) VALUES (37, 'Amares', 3);
INSERT INTO public.municipality (id, name, district_id) VALUES (38, 'Barcelos', 3);
INSERT INTO public.municipality (id, name, district_id) VALUES (39, 'Braga', 3);
INSERT INTO public.municipality (id, name, district_id) VALUES (40, 'Cabeceiras de Basto', 3);
INSERT INTO public.municipality (id, name, district_id) VALUES (41, 'Celorico de Basto', 3);
INSERT INTO public.municipality (id, name, district_id) VALUES (42, 'Esposende', 3);
INSERT INTO public.municipality (id, name, district_id) VALUES (43, 'Fafe', 3);
INSERT INTO public.municipality (id, name, district_id) VALUES (44, 'Guimarães', 3);
INSERT INTO public.municipality (id, name, district_id) VALUES (45, 'Póvoa de Lanhoso', 3);
INSERT INTO public.municipality (id, name, district_id) VALUES (46, 'Terras de Bouro', 3);
INSERT INTO public.municipality (id, name, district_id) VALUES (47, 'Vieira do Minho', 3);
INSERT INTO public.municipality (id, name, district_id) VALUES (48, 'Vila Nova de Famalicão', 3);
INSERT INTO public.municipality (id, name, district_id) VALUES (49, 'Vila Verde', 3);
INSERT INTO public.municipality (id, name, district_id) VALUES (50, 'Vizela', 3);
INSERT INTO public.municipality (id, name, district_id) VALUES (51, 'todos', 4);
INSERT INTO public.municipality (id, name, district_id) VALUES (52, 'Alfândega da fé', 4);
INSERT INTO public.municipality (id, name, district_id) VALUES (53, 'Bragança', 4);
INSERT INTO public.municipality (id, name, district_id) VALUES (54, 'Carrazeda de Ansiães', 4);
INSERT INTO public.municipality (id, name, district_id) VALUES (55, 'Freixo de Espada à Cinta', 4);
INSERT INTO public.municipality (id, name, district_id) VALUES (56, 'Macedo de Cavaleiros', 4);
INSERT INTO public.municipality (id, name, district_id) VALUES (57, 'Miranda do Douro', 4);
INSERT INTO public.municipality (id, name, district_id) VALUES (58, 'Mirandela', 4);
INSERT INTO public.municipality (id, name, district_id) VALUES (59, 'Mogadouro', 4);
INSERT INTO public.municipality (id, name, district_id) VALUES (60, 'Torre de Moncorvo', 4);
INSERT INTO public.municipality (id, name, district_id) VALUES (61, 'Vila Flor', 4);
INSERT INTO public.municipality (id, name, district_id) VALUES (62, 'Vimioso', 4);
INSERT INTO public.municipality (id, name, district_id) VALUES (63, 'Vinhais', 4);
INSERT INTO public.municipality (id, name, district_id) VALUES (64, 'todos', 5);
INSERT INTO public.municipality (id, name, district_id) VALUES (65, 'Belmonte', 5);
INSERT INTO public.municipality (id, name, district_id) VALUES (66, 'Castelo Branco', 5);
INSERT INTO public.municipality (id, name, district_id) VALUES (67, 'Covilhã', 5);
INSERT INTO public.municipality (id, name, district_id) VALUES (68, 'Fundão', 5);
INSERT INTO public.municipality (id, name, district_id) VALUES (69, 'Idanha-a-nova', 5);
INSERT INTO public.municipality (id, name, district_id) VALUES (70, 'Oleiros', 5);
INSERT INTO public.municipality (id, name, district_id) VALUES (71, 'Penamacor', 5);
INSERT INTO public.municipality (id, name, district_id) VALUES (72, 'Proença-a-nova', 5);
INSERT INTO public.municipality (id, name, district_id) VALUES (73, 'Sertã', 5);
INSERT INTO public.municipality (id, name, district_id) VALUES (74, 'Vila de Rei', 5);
INSERT INTO public.municipality (id, name, district_id) VALUES (75, 'Vila Velha de Ródão', 5);
INSERT INTO public.municipality (id, name, district_id) VALUES (76, 'todos', 6);
INSERT INTO public.municipality (id, name, district_id) VALUES (77, 'Arganil', 6);
INSERT INTO public.municipality (id, name, district_id) VALUES (78, 'Cantanhede', 6);
INSERT INTO public.municipality (id, name, district_id) VALUES (79, 'Coimbra', 6);
INSERT INTO public.municipality (id, name, district_id) VALUES (80, 'Condeixa-a-nova', 6);
INSERT INTO public.municipality (id, name, district_id) VALUES (81, 'Figueira da Foz', 6);
INSERT INTO public.municipality (id, name, district_id) VALUES (82, 'Góis', 6);
INSERT INTO public.municipality (id, name, district_id) VALUES (83, 'Lousã', 6);
INSERT INTO public.municipality (id, name, district_id) VALUES (84, 'Mira', 6);
INSERT INTO public.municipality (id, name, district_id) VALUES (85, 'Miranda do Corvo', 6);
INSERT INTO public.municipality (id, name, district_id) VALUES (86, 'Montemor-o-velho', 6);
INSERT INTO public.municipality (id, name, district_id) VALUES (87, 'Oliveira do Hospital', 6);
INSERT INTO public.municipality (id, name, district_id) VALUES (88, 'Pampilhosa da Serra', 6);
INSERT INTO public.municipality (id, name, district_id) VALUES (89, 'Penacova', 6);
INSERT INTO public.municipality (id, name, district_id) VALUES (90, 'Penela', 6);
INSERT INTO public.municipality (id, name, district_id) VALUES (91, 'Soure', 6);
INSERT INTO public.municipality (id, name, district_id) VALUES (92, 'Tábua', 6);
INSERT INTO public.municipality (id, name, district_id) VALUES (93, 'Vila Nova de Poiares', 6);
INSERT INTO public.municipality (id, name, district_id) VALUES (94, 'todos', 7);
INSERT INTO public.municipality (id, name, district_id) VALUES (95, 'Albufeira', 7);
INSERT INTO public.municipality (id, name, district_id) VALUES (96, 'Alcoutim', 7);
INSERT INTO public.municipality (id, name, district_id) VALUES (97, 'Aljezur', 7);
INSERT INTO public.municipality (id, name, district_id) VALUES (98, 'Castro Marim', 7);
INSERT INTO public.municipality (id, name, district_id) VALUES (99, 'Faro', 7);
INSERT INTO public.municipality (id, name, district_id) VALUES (100, 'Lagoa', 7);
INSERT INTO public.municipality (id, name, district_id) VALUES (101, 'Lagos', 7);
INSERT INTO public.municipality (id, name, district_id) VALUES (102, 'Loulé', 7);
INSERT INTO public.municipality (id, name, district_id) VALUES (103, 'Monchique', 7);
INSERT INTO public.municipality (id, name, district_id) VALUES (104, 'Olhão', 7);
INSERT INTO public.municipality (id, name, district_id) VALUES (105, 'Portimão', 7);
INSERT INTO public.municipality (id, name, district_id) VALUES (106, 'São Brás de Alportel', 7);
INSERT INTO public.municipality (id, name, district_id) VALUES (107, 'Silves', 7);
INSERT INTO public.municipality (id, name, district_id) VALUES (108, 'Tavira', 7);
INSERT INTO public.municipality (id, name, district_id) VALUES (109, 'Vila do Bispo', 7);
INSERT INTO public.municipality (id, name, district_id) VALUES (110, 'Vila Real de Santo António', 7);
INSERT INTO public.municipality (id, name, district_id) VALUES (111, 'todos', 8);
INSERT INTO public.municipality (id, name, district_id) VALUES (112, 'Aguiar da Beira', 8);
INSERT INTO public.municipality (id, name, district_id) VALUES (113, 'Almeida', 8);
INSERT INTO public.municipality (id, name, district_id) VALUES (114, 'Celorico da Beira', 8);
INSERT INTO public.municipality (id, name, district_id) VALUES (115, 'Figueira de Castelo Rodrigo', 8);
INSERT INTO public.municipality (id, name, district_id) VALUES (116, 'Fornos de Algodres', 8);
INSERT INTO public.municipality (id, name, district_id) VALUES (117, 'Gouveia', 8);
INSERT INTO public.municipality (id, name, district_id) VALUES (118, 'Guarda', 8);
INSERT INTO public.municipality (id, name, district_id) VALUES (119, 'Manteigas', 8);
INSERT INTO public.municipality (id, name, district_id) VALUES (120, 'Mêda', 8);
INSERT INTO public.municipality (id, name, district_id) VALUES (121, 'Pinhel', 8);
INSERT INTO public.municipality (id, name, district_id) VALUES (122, 'Sabugal', 8);
INSERT INTO public.municipality (id, name, district_id) VALUES (123, 'Seia', 8);
INSERT INTO public.municipality (id, name, district_id) VALUES (124, 'Trancoso', 8);
INSERT INTO public.municipality (id, name, district_id) VALUES (125, 'Vila Nova de Foz Côa', 8);
INSERT INTO public.municipality (id, name, district_id) VALUES (126, 'todos', 9);
INSERT INTO public.municipality (id, name, district_id) VALUES (127, 'Alcobaça', 9);
INSERT INTO public.municipality (id, name, district_id) VALUES (128, 'Alvaiázere', 9);
INSERT INTO public.municipality (id, name, district_id) VALUES (129, 'Ansião', 9);
INSERT INTO public.municipality (id, name, district_id) VALUES (130, 'Batalha', 9);
INSERT INTO public.municipality (id, name, district_id) VALUES (131, 'Bombarral', 9);
INSERT INTO public.municipality (id, name, district_id) VALUES (132, 'Caldas da Rainha', 9);
INSERT INTO public.municipality (id, name, district_id) VALUES (133, 'Castanheira de Pêra', 9);
INSERT INTO public.municipality (id, name, district_id) VALUES (134, 'Figueiró Dos Vinhos', 9);
INSERT INTO public.municipality (id, name, district_id) VALUES (135, 'Leiria', 9);
INSERT INTO public.municipality (id, name, district_id) VALUES (136, 'Marinha Grande', 9);
INSERT INTO public.municipality (id, name, district_id) VALUES (137, 'Nazaré', 9);
INSERT INTO public.municipality (id, name, district_id) VALUES (138, 'Óbidos', 9);
INSERT INTO public.municipality (id, name, district_id) VALUES (139, 'Pedrógão Grande', 9);
INSERT INTO public.municipality (id, name, district_id) VALUES (140, 'Peniche', 9);
INSERT INTO public.municipality (id, name, district_id) VALUES (141, 'Pombal', 9);
INSERT INTO public.municipality (id, name, district_id) VALUES (142, 'Porto de Mós', 9);
INSERT INTO public.municipality (id, name, district_id) VALUES (143, 'todos', 10);
INSERT INTO public.municipality (id, name, district_id) VALUES (144, 'Alenquer', 10);
INSERT INTO public.municipality (id, name, district_id) VALUES (145, 'Amadora', 10);
INSERT INTO public.municipality (id, name, district_id) VALUES (146, 'Arruda Dos Vinhos', 10);
INSERT INTO public.municipality (id, name, district_id) VALUES (147, 'Azambuja', 10);
INSERT INTO public.municipality (id, name, district_id) VALUES (148, 'Cadaval', 10);
INSERT INTO public.municipality (id, name, district_id) VALUES (149, 'Cascais', 10);
INSERT INTO public.municipality (id, name, district_id) VALUES (150, 'Lisboa', 10);
INSERT INTO public.municipality (id, name, district_id) VALUES (151, 'Loures', 10);
INSERT INTO public.municipality (id, name, district_id) VALUES (152, 'Lourinhã', 10);
INSERT INTO public.municipality (id, name, district_id) VALUES (153, 'Mafra', 10);
INSERT INTO public.municipality (id, name, district_id) VALUES (154, 'Odivelas', 10);
INSERT INTO public.municipality (id, name, district_id) VALUES (155, 'Oeiras', 10);
INSERT INTO public.municipality (id, name, district_id) VALUES (156, 'Sintra', 10);
INSERT INTO public.municipality (id, name, district_id) VALUES (157, 'Sobral de Monte Agraço', 10);
INSERT INTO public.municipality (id, name, district_id) VALUES (158, 'Torres Vedras', 10);
INSERT INTO public.municipality (id, name, district_id) VALUES (159, 'Vila Franca de Xira', 10);
INSERT INTO public.municipality (id, name, district_id) VALUES (160, 'todos', 11);
INSERT INTO public.municipality (id, name, district_id) VALUES (161, 'Alter do Chão', 11);
INSERT INTO public.municipality (id, name, district_id) VALUES (162, 'Arronches', 11);
INSERT INTO public.municipality (id, name, district_id) VALUES (163, 'Avis', 11);
INSERT INTO public.municipality (id, name, district_id) VALUES (164, 'Campo Maior', 11);
INSERT INTO public.municipality (id, name, district_id) VALUES (165, 'Castelo de Vide', 11);
INSERT INTO public.municipality (id, name, district_id) VALUES (166, 'Crato', 11);
INSERT INTO public.municipality (id, name, district_id) VALUES (167, 'Elvas', 11);
INSERT INTO public.municipality (id, name, district_id) VALUES (168, 'Fronteira', 11);
INSERT INTO public.municipality (id, name, district_id) VALUES (169, 'Gavião', 11);
INSERT INTO public.municipality (id, name, district_id) VALUES (170, 'Marvão', 11);
INSERT INTO public.municipality (id, name, district_id) VALUES (171, 'Monforte', 11);
INSERT INTO public.municipality (id, name, district_id) VALUES (172, 'Nisa', 11);
INSERT INTO public.municipality (id, name, district_id) VALUES (173, 'Ponte de Sor', 11);
INSERT INTO public.municipality (id, name, district_id) VALUES (174, 'Portalegre', 11);
INSERT INTO public.municipality (id, name, district_id) VALUES (175, 'Sousel', 11);
INSERT INTO public.municipality (id, name, district_id) VALUES (176, 'todos', 12);
INSERT INTO public.municipality (id, name, district_id) VALUES (177, 'Amarante', 12);
INSERT INTO public.municipality (id, name, district_id) VALUES (178, 'Baião', 12);
INSERT INTO public.municipality (id, name, district_id) VALUES (179, 'Felgueiras', 12);
INSERT INTO public.municipality (id, name, district_id) VALUES (180, 'Gondomar', 12);
INSERT INTO public.municipality (id, name, district_id) VALUES (181, 'Lousada', 12);
INSERT INTO public.municipality (id, name, district_id) VALUES (182, 'Maia', 12);
INSERT INTO public.municipality (id, name, district_id) VALUES (183, 'Marco de Canaveses', 12);
INSERT INTO public.municipality (id, name, district_id) VALUES (184, 'Matosinhos', 12);
INSERT INTO public.municipality (id, name, district_id) VALUES (185, 'Paços de Ferreira', 12);
INSERT INTO public.municipality (id, name, district_id) VALUES (186, 'Paredes', 12);
INSERT INTO public.municipality (id, name, district_id) VALUES (187, 'Penafiel', 12);
INSERT INTO public.municipality (id, name, district_id) VALUES (188, 'Porto', 12);
INSERT INTO public.municipality (id, name, district_id) VALUES (189, 'Póvoa de Varzim', 12);
INSERT INTO public.municipality (id, name, district_id) VALUES (190, 'Santo Tirso', 12);
INSERT INTO public.municipality (id, name, district_id) VALUES (191, 'Trofa', 12);
INSERT INTO public.municipality (id, name, district_id) VALUES (192, 'Valongo', 12);
INSERT INTO public.municipality (id, name, district_id) VALUES (193, 'Vila do Conde', 12);
INSERT INTO public.municipality (id, name, district_id) VALUES (194, 'Vila Nova de Gaia', 12);
INSERT INTO public.municipality (id, name, district_id) VALUES (195, 'todos', 13);
INSERT INTO public.municipality (id, name, district_id) VALUES (196, 'Angra do Heroísmo', 13);
INSERT INTO public.municipality (id, name, district_id) VALUES (197, 'Calheta de São Jorge', 13);
INSERT INTO public.municipality (id, name, district_id) VALUES (198, 'Corvo', 13);
INSERT INTO public.municipality (id, name, district_id) VALUES (199, 'Horta', 13);
INSERT INTO public.municipality (id, name, district_id) VALUES (200, 'Lagoa (açores)', 13);
INSERT INTO public.municipality (id, name, district_id) VALUES (201, 'Lajes Das Flores', 13);
INSERT INTO public.municipality (id, name, district_id) VALUES (202, 'Lajes do Pico', 13);
INSERT INTO public.municipality (id, name, district_id) VALUES (203, 'Madalena', 13);
INSERT INTO public.municipality (id, name, district_id) VALUES (204, 'Nordeste', 13);
INSERT INTO public.municipality (id, name, district_id) VALUES (205, 'Ponta Delgada', 13);
INSERT INTO public.municipality (id, name, district_id) VALUES (206, 'Povoação', 13);
INSERT INTO public.municipality (id, name, district_id) VALUES (207, 'Praia da Vitória', 13);
INSERT INTO public.municipality (id, name, district_id) VALUES (208, 'Ribeira Grande', 13);
INSERT INTO public.municipality (id, name, district_id) VALUES (209, 'Santa Cruz da Graciosa', 13);
INSERT INTO public.municipality (id, name, district_id) VALUES (210, 'Santa Cruz Das Flores', 13);
INSERT INTO public.municipality (id, name, district_id) VALUES (211, 'São Roque do Pico', 13);
INSERT INTO public.municipality (id, name, district_id) VALUES (212, 'Velas', 13);
INSERT INTO public.municipality (id, name, district_id) VALUES (213, 'Vila do Porto', 13);
INSERT INTO public.municipality (id, name, district_id) VALUES (214, 'Vila Franca do Campo', 13);
INSERT INTO public.municipality (id, name, district_id) VALUES (215, 'todos', 14);
INSERT INTO public.municipality (id, name, district_id) VALUES (216, 'Calheta', 14);
INSERT INTO public.municipality (id, name, district_id) VALUES (217, 'Câmara de Lobos', 14);
INSERT INTO public.municipality (id, name, district_id) VALUES (218, 'Funchal', 14);
INSERT INTO public.municipality (id, name, district_id) VALUES (219, 'Machico', 14);
INSERT INTO public.municipality (id, name, district_id) VALUES (220, 'Ponta do Sol', 14);
INSERT INTO public.municipality (id, name, district_id) VALUES (221, 'Porto Moniz', 14);
INSERT INTO public.municipality (id, name, district_id) VALUES (222, 'Porto Santo', 14);
INSERT INTO public.municipality (id, name, district_id) VALUES (223, 'Ribeira Brava', 14);
INSERT INTO public.municipality (id, name, district_id) VALUES (224, 'Santa Cruz', 14);
INSERT INTO public.municipality (id, name, district_id) VALUES (225, 'Santana', 14);
INSERT INTO public.municipality (id, name, district_id) VALUES (226, 'São Vicente', 14);
INSERT INTO public.municipality (id, name, district_id) VALUES (227, 'todos', 15);
INSERT INTO public.municipality (id, name, district_id) VALUES (228, 'Abrantes', 15);
INSERT INTO public.municipality (id, name, district_id) VALUES (229, 'Alcanena', 15);
INSERT INTO public.municipality (id, name, district_id) VALUES (230, 'Almeirim', 15);
INSERT INTO public.municipality (id, name, district_id) VALUES (231, 'Alpiarça', 15);
INSERT INTO public.municipality (id, name, district_id) VALUES (232, 'Benavente', 15);
INSERT INTO public.municipality (id, name, district_id) VALUES (233, 'Cartaxo', 15);
INSERT INTO public.municipality (id, name, district_id) VALUES (234, 'Chamusca', 15);
INSERT INTO public.municipality (id, name, district_id) VALUES (235, 'Constância', 15);
INSERT INTO public.municipality (id, name, district_id) VALUES (236, 'Coruche', 15);
INSERT INTO public.municipality (id, name, district_id) VALUES (237, 'Entroncamento', 15);
INSERT INTO public.municipality (id, name, district_id) VALUES (238, 'Ferreira do Zêzere', 15);
INSERT INTO public.municipality (id, name, district_id) VALUES (239, 'Golegã', 15);
INSERT INTO public.municipality (id, name, district_id) VALUES (240, 'Mação', 15);
INSERT INTO public.municipality (id, name, district_id) VALUES (241, 'Ourém', 15);
INSERT INTO public.municipality (id, name, district_id) VALUES (242, 'Rio Maior', 15);
INSERT INTO public.municipality (id, name, district_id) VALUES (243, 'Salvaterra de Magos', 15);
INSERT INTO public.municipality (id, name, district_id) VALUES (244, 'Santarém', 15);
INSERT INTO public.municipality (id, name, district_id) VALUES (245, 'Sardoal', 15);
INSERT INTO public.municipality (id, name, district_id) VALUES (246, 'Tomar', 15);
INSERT INTO public.municipality (id, name, district_id) VALUES (247, 'Torres Novas', 15);
INSERT INTO public.municipality (id, name, district_id) VALUES (248, 'Vila Nova da Barquinha', 15);
INSERT INTO public.municipality (id, name, district_id) VALUES (249, 'todos', 16);
INSERT INTO public.municipality (id, name, district_id) VALUES (250, 'Alcácer do Sal', 16);
INSERT INTO public.municipality (id, name, district_id) VALUES (251, 'Alcochete', 16);
INSERT INTO public.municipality (id, name, district_id) VALUES (252, 'Almada', 16);
INSERT INTO public.municipality (id, name, district_id) VALUES (253, 'Barreiro', 16);
INSERT INTO public.municipality (id, name, district_id) VALUES (254, 'Grândola', 16);
INSERT INTO public.municipality (id, name, district_id) VALUES (255, 'Moita', 16);
INSERT INTO public.municipality (id, name, district_id) VALUES (256, 'Montijo', 16);
INSERT INTO public.municipality (id, name, district_id) VALUES (257, 'Palmela', 16);
INSERT INTO public.municipality (id, name, district_id) VALUES (258, 'Santiago do Cacém', 16);
INSERT INTO public.municipality (id, name, district_id) VALUES (259, 'Seixal', 16);
INSERT INTO public.municipality (id, name, district_id) VALUES (260, 'Sesimbra', 16);
INSERT INTO public.municipality (id, name, district_id) VALUES (261, 'Setúbal', 16);
INSERT INTO public.municipality (id, name, district_id) VALUES (262, 'Sines', 16);
INSERT INTO public.municipality (id, name, district_id) VALUES (263, 'todos', 17);
INSERT INTO public.municipality (id, name, district_id) VALUES (264, 'Arcos de Valdevez', 17);
INSERT INTO public.municipality (id, name, district_id) VALUES (265, 'Caminha', 17);
INSERT INTO public.municipality (id, name, district_id) VALUES (266, 'Melgaço', 17);
INSERT INTO public.municipality (id, name, district_id) VALUES (267, 'Monção', 17);
INSERT INTO public.municipality (id, name, district_id) VALUES (268, 'Paredes de Coura', 17);
INSERT INTO public.municipality (id, name, district_id) VALUES (269, 'Ponte da Barca', 17);
INSERT INTO public.municipality (id, name, district_id) VALUES (270, 'Ponte de Lima', 17);
INSERT INTO public.municipality (id, name, district_id) VALUES (271, 'Valença', 17);
INSERT INTO public.municipality (id, name, district_id) VALUES (272, 'Viana do Castelo', 17);
INSERT INTO public.municipality (id, name, district_id) VALUES (273, 'Vila Nova de Cerveira', 17);
INSERT INTO public.municipality (id, name, district_id) VALUES (274, 'todos', 18);
INSERT INTO public.municipality (id, name, district_id) VALUES (275, 'Alijó', 18);
INSERT INTO public.municipality (id, name, district_id) VALUES (276, 'Boticas', 18);
INSERT INTO public.municipality (id, name, district_id) VALUES (277, 'Chaves', 18);
INSERT INTO public.municipality (id, name, district_id) VALUES (278, 'Mesão Frio', 18);
INSERT INTO public.municipality (id, name, district_id) VALUES (279, 'Mondim de Basto', 18);
INSERT INTO public.municipality (id, name, district_id) VALUES (280, 'Montalegre', 18);
INSERT INTO public.municipality (id, name, district_id) VALUES (281, 'Murça', 18);
INSERT INTO public.municipality (id, name, district_id) VALUES (282, 'Peso da Régua', 18);
INSERT INTO public.municipality (id, name, district_id) VALUES (283, 'Ribeira de Pena', 18);
INSERT INTO public.municipality (id, name, district_id) VALUES (284, 'Sabrosa', 18);
INSERT INTO public.municipality (id, name, district_id) VALUES (285, 'Santa Marta de Penaguião', 18);
INSERT INTO public.municipality (id, name, district_id) VALUES (286, 'Valpaços', 18);
INSERT INTO public.municipality (id, name, district_id) VALUES (287, 'Vila Pouca de Aguiar', 18);
INSERT INTO public.municipality (id, name, district_id) VALUES (288, 'Vila Real', 18);
INSERT INTO public.municipality (id, name, district_id) VALUES (289, 'todos', 19);
INSERT INTO public.municipality (id, name, district_id) VALUES (290, 'Armamar', 19);
INSERT INTO public.municipality (id, name, district_id) VALUES (291, 'Carregal do Sal', 19);
INSERT INTO public.municipality (id, name, district_id) VALUES (292, 'Castro Daire', 19);
INSERT INTO public.municipality (id, name, district_id) VALUES (293, 'Cinfães', 19);
INSERT INTO public.municipality (id, name, district_id) VALUES (294, 'Lamego', 19);
INSERT INTO public.municipality (id, name, district_id) VALUES (295, 'Mangualde', 19);
INSERT INTO public.municipality (id, name, district_id) VALUES (296, 'Moimenta da Beira', 19);
INSERT INTO public.municipality (id, name, district_id) VALUES (297, 'Mortágua', 19);
INSERT INTO public.municipality (id, name, district_id) VALUES (298, 'Nelas', 19);
INSERT INTO public.municipality (id, name, district_id) VALUES (299, 'Oliveira de Frades', 19);
INSERT INTO public.municipality (id, name, district_id) VALUES (300, 'Penalva do Castelo', 19);
INSERT INTO public.municipality (id, name, district_id) VALUES (301, 'Penedono', 19);
INSERT INTO public.municipality (id, name, district_id) VALUES (302, 'Resende', 19);
INSERT INTO public.municipality (id, name, district_id) VALUES (303, 'Santa Comba Dão', 19);
INSERT INTO public.municipality (id, name, district_id) VALUES (304, 'São João da Pesqueira', 19);
INSERT INTO public.municipality (id, name, district_id) VALUES (305, 'São Pedro do Sul', 19);
INSERT INTO public.municipality (id, name, district_id) VALUES (306, 'Sátão', 19);
INSERT INTO public.municipality (id, name, district_id) VALUES (307, 'Sernancelhe', 19);
INSERT INTO public.municipality (id, name, district_id) VALUES (308, 'Tabuaço', 19);
INSERT INTO public.municipality (id, name, district_id) VALUES (309, 'Tarouca', 19);
INSERT INTO public.municipality (id, name, district_id) VALUES (310, 'Tondela', 19);
INSERT INTO public.municipality (id, name, district_id) VALUES (311, 'Vila Nova de Paiva', 19);
INSERT INTO public.municipality (id, name, district_id) VALUES (312, 'Viseu', 19);
INSERT INTO public.municipality (id, name, district_id) VALUES (313, 'Vouzela', 19);
INSERT INTO public.municipality (id, name, district_id) VALUES (314, 'todos', 20);
INSERT INTO public.municipality (id, name, district_id) VALUES (315, 'Alandroal', 20);
INSERT INTO public.municipality (id, name, district_id) VALUES (316, 'Arraiolos', 20);
INSERT INTO public.municipality (id, name, district_id) VALUES (317, 'Borba', 20);
INSERT INTO public.municipality (id, name, district_id) VALUES (318, 'Estremoz', 20);
INSERT INTO public.municipality (id, name, district_id) VALUES (319, 'Évora', 20);
INSERT INTO public.municipality (id, name, district_id) VALUES (320, 'Montemor-o-novo', 20);
INSERT INTO public.municipality (id, name, district_id) VALUES (321, 'Mora', 20);
INSERT INTO public.municipality (id, name, district_id) VALUES (322, 'Mourão', 20);
INSERT INTO public.municipality (id, name, district_id) VALUES (323, 'Portel', 20);
INSERT INTO public.municipality (id, name, district_id) VALUES (324, 'Redondo', 20);
INSERT INTO public.municipality (id, name, district_id) VALUES (325, 'Reguengos de Monsaraz', 20);
INSERT INTO public.municipality (id, name, district_id) VALUES (326, 'Vendas Novas', 20);
INSERT INTO public.municipality (id, name, district_id) VALUES (327, 'Viana do Alentejo', 20);
INSERT INTO public.municipality (id, name, district_id) VALUES (328, 'Vila Viçosa', 20);